/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/bom-lines/{line_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Bom Line */
    get: operations["get_bom_line_api_v1_bom_lines__line_id__get"];
    put?: never;
    post?: never;
    /** Delete Bom Line */
    delete: operations["delete_bom_line_api_v1_bom_lines__line_id__delete"];
    options?: never;
    head?: never;
    /** Update Bom Line */
    patch: operations["update_bom_line_api_v1_bom_lines__line_id__patch"];
    trace?: never;
  };
  "/api/v1/builds/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Build */
    get: operations["get_build_api_v1_builds__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Build */
    patch: operations["update_build_api_v1_builds__ref__patch"];
    trace?: never;
  };
  "/api/v1/calibers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Calibers */
    get: operations["list_calibers_api_v1_calibers_get"];
    put?: never;
    /** Create Caliber */
    post: operations["create_caliber_api_v1_calibers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/calibers/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Caliber */
    get: operations["get_caliber_api_v1_calibers__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Caliber */
    patch: operations["update_caliber_api_v1_calibers__ref__patch"];
    trace?: never;
  };
  "/api/v1/calibers/{ref}/bom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Caliber Bom */
    get: operations["get_caliber_bom_api_v1_calibers__ref__bom_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Components */
    get: operations["list_components_api_v1_components_get"];
    put?: never;
    /** Create Component */
    post: operations["create_component_api_v1_components_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Component */
    get: operations["get_component_api_v1_components__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Component */
    patch: operations["update_component_api_v1_components__ref__patch"];
    trace?: never;
  };
  "/api/v1/components/{ref}/bom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Component Bom
     * @description BOM of the component's latest revision.
     */
    get: operations["get_component_bom_api_v1_components__ref__bom_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components/{ref}/part-instances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Component Part Instances */
    get: operations["component_part_instances_api_v1_components__ref__part_instances_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components/{ref}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Revisions */
    get: operations["list_revisions_api_v1_components__ref__revisions_get"];
    put?: never;
    /** Create Revision */
    post: operations["create_revision_api_v1_components__ref__revisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components/{ref}/revisions/{label}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Revision By Label */
    get: operations["get_revision_by_label_api_v1_components__ref__revisions__label__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/components/{ref}/where-used": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Where Used */
    get: operations["get_where_used_api_v1_components__ref__where_used_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dashboard Summary */
    get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Models */
    get: operations["list_models_api_v1_models_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Model */
    get: operations["get_model_api_v1_models__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Model */
    patch: operations["update_model_api_v1_models__ref__patch"];
    trace?: never;
  };
  "/api/v1/models/{ref}/bom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Model Bom */
    get: operations["get_model_bom_api_v1_models__ref__bom_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/part-instances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Part Instances */
    get: operations["list_part_instances_api_v1_part_instances_get"];
    put?: never;
    /** Create Part Instances */
    post: operations["create_part_instances_api_v1_part_instances_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/part-instances/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Part Instance */
    get: operations["get_part_instance_api_v1_part_instances__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Part Instance */
    patch: operations["update_part_instance_api_v1_part_instances__ref__patch"];
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations["list_products_api_v1_products_get"];
    put?: never;
    /** Create Product */
    post: operations["create_product_api_v1_products_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations["get_product_api_v1_products__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations["update_product_api_v1_products__ref__patch"];
    trace?: never;
  };
  "/api/v1/products/{ref}/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Product Models */
    get: operations["list_product_models_api_v1_products__ref__models_get"];
    put?: never;
    /** Create Product Model */
    post: operations["create_product_model_api_v1_products__ref__models_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/prototypes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Prototypes */
    get: operations["list_prototypes_api_v1_prototypes_get"];
    put?: never;
    /** Create Prototype */
    post: operations["create_prototype_api_v1_prototypes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/prototypes/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Prototype */
    get: operations["get_prototype_api_v1_prototypes__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Prototype */
    patch: operations["update_prototype_api_v1_prototypes__ref__patch"];
    trace?: never;
  };
  "/api/v1/prototypes/{ref}/builds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Builds */
    get: operations["list_builds_api_v1_prototypes__ref__builds_get"];
    put?: never;
    /** Create Build */
    post: operations["create_build_api_v1_prototypes__ref__builds_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/prototypes/{ref}/configuration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Configuration */
    get: operations["get_configuration_api_v1_prototypes__ref__configuration_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Revision */
    get: operations["get_revision_api_v1_revisions__revision_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Revision */
    patch: operations["update_revision_api_v1_revisions__revision_id__patch"];
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}/bom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Bom Tree */
    get: operations["get_bom_tree_api_v1_revisions__revision_id__bom_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}/bom-lines": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Bom Line */
    post: operations["add_bom_line_api_v1_revisions__revision_id__bom_lines_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}/bom/flat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Bom Flat */
    get: operations["get_bom_flat_api_v1_revisions__revision_id__bom_flat_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}/prototypes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Revision Prototypes
     * @description Prototypes that currently contain a part made to this exact revision.
     */
    get: operations["revision_prototypes_api_v1_revisions__revision_id__prototypes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/revisions/{revision_id}/transition": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Revision */
    post: operations["transition_revision_api_v1_revisions__revision_id__transition_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** System Info */
    get: operations["system_info_api_v1_system_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BomFlat */
    BomFlat: {
      /**
       * Mode
       * @enum {string}
       */
      mode: "latest" | "released";
      root_component: components["schemas"]["ComponentSummary"];
      root_revision: components["schemas"]["RevisionSummary"];
      /** Rows */
      rows: components["schemas"]["BomFlatRow"][];
    };
    /** BomFlatRow */
    BomFlatRow: {
      component: components["schemas"]["ComponentSummary"];
      /** Extended Quantity */
      extended_quantity: string;
      /** Find Number */
      find_number: number;
      /** Is Pinned */
      is_pinned: boolean;
      /** Level */
      level: number;
      /** Path */
      path: string[];
      /** Quantity */
      quantity: string;
      /** Reference Designator */
      reference_designator: string | null;
      /**
       * Resolution
       * @enum {string}
       */
      resolution: "pinned" | "latest" | "released" | "unresolved";
      revision: components["schemas"]["RevisionSummary"] | null;
      /** Unit */
      unit: string;
    };
    /** BomLineCreate */
    BomLineCreate: {
      /** Child Component Id */
      child_component_id?: string | null;
      /** Child Component Identifier */
      child_component_identifier?: string | null;
      /**
       * Child Revision Id
       * @description Pin to an exact child revision. Null resolves at query time.
       */
      child_revision_id?: string | null;
      /**
       * Find Number
       * @description Defaults to max + 10.
       */
      find_number?: number | null;
      /** Notes */
      notes?: string | null;
      /**
       * Quantity
       * @default 1
       */
      quantity?: number | string;
      /** Reference Designator */
      reference_designator?: string | null;
      /**
       * Unit
       * @default ea
       */
      unit?: string;
    };
    /** BomLineRead */
    BomLineRead: {
      child_component: components["schemas"]["ComponentSummary"];
      child_revision: components["schemas"]["RevisionSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Find Number */
      find_number: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Pinned */
      is_pinned: boolean;
      /** Notes */
      notes: string | null;
      /**
       * Parent Revision Id
       * Format: uuid
       */
      parent_revision_id: string;
      /** Quantity */
      quantity: string;
      /** Reference Designator */
      reference_designator: string | null;
      /** Unit */
      unit: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** BomLineUpdate */
    BomLineUpdate: {
      /** Child Revision Id */
      child_revision_id?: string | null;
      /** Find Number */
      find_number?: number | null;
      /** Notes */
      notes?: string | null;
      /** Quantity */
      quantity?: number | string | null;
      /** Reference Designator */
      reference_designator?: string | null;
      /** Unit */
      unit?: string | null;
    };
    /** BomNode */
    BomNode: {
      /** Children */
      children: components["schemas"]["BomNode"][];
      /** Level */
      level: number;
      line: components["schemas"]["BomLineRead"];
      /**
       * Resolution
       * @enum {string}
       */
      resolution: "pinned" | "latest" | "released" | "unresolved";
      resolved_revision: components["schemas"]["RevisionSummary"] | null;
    };
    /** BomTree */
    BomTree: {
      /** Line Count */
      line_count: number;
      /** Max Depth */
      max_depth: number;
      /**
       * Mode
       * @enum {string}
       */
      mode: "latest" | "released";
      /** Nodes */
      nodes: components["schemas"]["BomNode"][];
      root_component: components["schemas"]["ComponentSummary"];
      root_revision: components["schemas"]["RevisionSummary"];
      /** Unresolved Count */
      unresolved_count: number;
    };
    /**
     * BuildAction
     * @enum {string}
     */
    BuildAction: "INSTALL" | "REMOVE";
    /** BuildEntryCreate */
    BuildEntryCreate: {
      /** @default INSTALL */
      action?: components["schemas"]["BuildAction"];
      /** Notes */
      notes?: string | null;
      /** Part Instance Id */
      part_instance_id?: string | null;
      /** Part Instance Identifier */
      part_instance_identifier?: string | null;
      /** Position */
      position?: string | null;
    };
    /** BuildEntryRead */
    BuildEntryRead: {
      action: components["schemas"]["BuildAction"];
      component: components["schemas"]["ComponentSummary"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Notes */
      notes: string | null;
      part_instance: components["schemas"]["PartInstanceSummary"];
      /** Position */
      position: string | null;
      revision: components["schemas"]["RevisionSummary"];
      /** Sequence */
      sequence: number;
    };
    /** BuildRecordCreate */
    BuildRecordCreate: {
      /** Entries */
      entries?: components["schemas"]["BuildEntryCreate"][];
      /** Notes */
      notes?: string | null;
      /**
       * Performed By
       * @description Defaults to the current actor.
       */
      performed_by?: string | null;
      /**
       * Performed On
       * Format: date
       */
      performed_on: string;
      /**
       * Procedure
       * @description Steps, lubrication, torque and sequence as performed.
       */
      procedure?: string | null;
      /** Title */
      title: string;
    };
    /** BuildRecordRead */
    BuildRecordRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Entries */
      entries: components["schemas"]["BuildEntryRead"][];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Notes */
      notes: string | null;
      /** Performed By */
      performed_by: string;
      /**
       * Performed On
       * Format: date
       */
      performed_on: string;
      /** Procedure */
      procedure: string | null;
      prototype: components["schemas"]["PrototypeSummary"];
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** BuildRecordSummary */
    BuildRecordSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Performed By */
      performed_by: string;
      /**
       * Performed On
       * Format: date
       */
      performed_on: string;
      /** Title */
      title: string;
    };
    /** BuildRecordUpdate */
    BuildRecordUpdate: {
      /** Notes */
      notes?: string | null;
    };
    /** CaliberCreate */
    CaliberCreate: {
      /** Architecture */
      architecture?: string | null;
      /** Description */
      description?: string | null;
      /** Diameter Mm */
      diameter_mm?: number | string | null;
      /** Frequency Bph */
      frequency_bph?: number | null;
      /** Identifier */
      identifier: string;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      /** Jewel Count */
      jewel_count?: number | null;
      /** @default CONCEPT */
      lifecycle_state?: components["schemas"]["LifecycleState"];
      /** Lift Angle Deg */
      lift_angle_deg?: number | string | null;
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Power Reserve Hours */
      power_reserve_hours?: number | string | null;
      /** Root Component Id */
      root_component_id?: string | null;
      /**
       * Specification
       * @description Evolving fields: barrel configuration, gear ratios, tooth counts, balance inertia, hairspring, escapement geometry.
       */
      specification?: {
        [key: string]: unknown;
      } | null;
      /** Target Amplitude Deg */
      target_amplitude_deg?: number | null;
      /** Target Rate Tolerance Spd */
      target_rate_tolerance_spd?: number | string | null;
      /** Thickness Mm */
      thickness_mm?: number | string | null;
    };
    /** CaliberRead */
    CaliberRead: {
      /** Architecture */
      architecture?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description: string | null;
      /** Diameter Mm */
      diameter_mm?: string | null;
      /** Frequency Bph */
      frequency_bph?: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      /** Jewel Count */
      jewel_count?: number | null;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Lift Angle Deg */
      lift_angle_deg?: string | null;
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      /** Power Reserve Hours */
      power_reserve_hours?: string | null;
      root_component: components["schemas"]["ComponentSummary"] | null;
      /**
       * Specification
       * @description Evolving fields: barrel configuration, gear ratios, tooth counts, balance inertia, hairspring, escapement geometry.
       */
      specification?: {
        [key: string]: unknown;
      } | null;
      /** Target Amplitude Deg */
      target_amplitude_deg?: number | null;
      /** Target Rate Tolerance Spd */
      target_rate_tolerance_spd?: string | null;
      /** Thickness Mm */
      thickness_mm?: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** CaliberSummary */
    CaliberSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
    };
    /** CaliberUpdate */
    CaliberUpdate: {
      /** Architecture */
      architecture?: string | null;
      /** Description */
      description?: string | null;
      /** Diameter Mm */
      diameter_mm?: number | string | null;
      /** Frequency Bph */
      frequency_bph?: number | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      /** Jewel Count */
      jewel_count?: number | null;
      lifecycle_state?: components["schemas"]["LifecycleState"] | null;
      /** Lift Angle Deg */
      lift_angle_deg?: number | string | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Power Reserve Hours */
      power_reserve_hours?: number | string | null;
      /** Root Component Id */
      root_component_id?: string | null;
      /**
       * Specification
       * @description Evolving fields: barrel configuration, gear ratios, tooth counts, balance inertia, hairspring, escapement geometry.
       */
      specification?: {
        [key: string]: unknown;
      } | null;
      /** Target Amplitude Deg */
      target_amplitude_deg?: number | null;
      /** Target Rate Tolerance Spd */
      target_rate_tolerance_spd?: number | string | null;
      /** Thickness Mm */
      thickness_mm?: number | string | null;
    };
    /** ComponentCreate */
    ComponentCreate: {
      /**
       * Change Summary
       * @default Initial revision
       */
      change_summary?: string;
      /** Description */
      description?: string | null;
      family: components["schemas"]["ComponentFamily"];
      /**
       * Identifier
       * @description Explicit identifier such as N1-MVT-002. Generated from product_code + family when omitted.
       */
      identifier?: string | null;
      initial_revision?: components["schemas"]["RevisionContent"] | null;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      kind: components["schemas"]["ComponentKind"];
      /** Name */
      name: string;
      /**
       * Product Code
       * @description Product code used to generate an identifier, e.g. N1.
       */
      product_code?: string | null;
    };
    /** ComponentDetail */
    ComponentDetail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description: string | null;
      family: components["schemas"]["ComponentFamily"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      kind: components["schemas"]["ComponentKind"];
      latest_revision: components["schemas"]["RevisionSummary"] | null;
      /** Name */
      name: string;
      released_revision: components["schemas"]["RevisionSummary"] | null;
      /** Revision Count */
      revision_count: number;
      /** Revisions */
      revisions: components["schemas"]["RevisionSummary"][];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /**
     * ComponentFamily
     * @enum {string}
     */
    ComponentFamily: "WATCH" | "CASE" | "DIAL" | "HAND" | "MVT" | "STRAP" | "PKG" | "MISC";
    /**
     * ComponentKind
     * @enum {string}
     */
    ComponentKind: "PART" | "ASSEMBLY";
    /** ComponentRead */
    ComponentRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description: string | null;
      family: components["schemas"]["ComponentFamily"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      kind: components["schemas"]["ComponentKind"];
      latest_revision: components["schemas"]["RevisionSummary"] | null;
      /** Name */
      name: string;
      released_revision: components["schemas"]["RevisionSummary"] | null;
      /** Revision Count */
      revision_count: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** ComponentSummary */
    ComponentSummary: {
      family: components["schemas"]["ComponentFamily"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      kind: components["schemas"]["ComponentKind"];
      /** Name */
      name: string;
    };
    /** ComponentUpdate */
    ComponentUpdate: {
      /** Description */
      description?: string | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      /** Name */
      name?: string | null;
    };
    /** ConfigurationRow */
    ConfigurationRow: {
      component: components["schemas"]["ComponentSummary"];
      installed_by: components["schemas"]["BuildRecordSummary"] | null;
      part_instance: components["schemas"]["PartInstanceSummary"];
      /** Position */
      position: string | null;
      revision: components["schemas"]["RevisionSummary"];
    };
    /** DashboardSummary */
    DashboardSummary: {
      active_prototype: components["schemas"]["PrototypeSummary"] | null;
      /** Assembly Count */
      assembly_count: number;
      /** Calibers */
      calibers: components["schemas"]["CaliberSummary"][];
      /** Component Count */
      component_count: number;
      /** Components By State */
      components_by_state: {
        [key: string]: number;
      };
      /** Products */
      products: components["schemas"]["ProductSummary"][];
      /** Prototype Count */
      prototype_count: number;
      /** Prototypes */
      prototypes: components["schemas"]["PrototypeSummary"][];
      /** Recent Revisions */
      recent_revisions: components["schemas"]["RecentRevision"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Database */
      database: string;
      /** Environment */
      environment: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * LifecycleState
     * @enum {string}
     */
    LifecycleState: "CONCEPT" | "DESIGN" | "PROTOTYPE" | "VALIDATION" | "RELEASED" | "OBSOLETE";
    /** Page[CaliberRead] */
    Page_CaliberRead_: {
      /** Items */
      items: components["schemas"]["CaliberRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[ComponentRead] */
    Page_ComponentRead_: {
      /** Items */
      items: components["schemas"]["ComponentRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[PartInstanceRead] */
    Page_PartInstanceRead_: {
      /** Items */
      items: components["schemas"]["PartInstanceRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[ProductRead] */
    Page_ProductRead_: {
      /** Items */
      items: components["schemas"]["ProductRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[PrototypeRead] */
    Page_PrototypeRead_: {
      /** Items */
      items: components["schemas"]["PrototypeRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** PartInstanceCreate */
    PartInstanceCreate: {
      /**
       * Component Revision Id
       * Format: uuid
       */
      component_revision_id: string;
      /** Heat Treatment Lot */
      heat_treatment_lot?: string | null;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      /** Lot */
      lot?: string | null;
      /** Material Lot */
      material_lot?: string | null;
      /** Notes */
      notes?: string | null;
      /**
       * Quantity
       * @description Create this many instances.
       * @default 1
       */
      quantity?: number;
      /** Serial Number */
      serial_number?: string | null;
      /** @default IN_HOUSE */
      source?: components["schemas"]["PartSource"];
      /** Supplier Note */
      supplier_note?: string | null;
    };
    /** PartInstanceRead */
    PartInstanceRead: {
      component: components["schemas"]["ComponentSummary"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      current_prototype: components["schemas"]["PrototypeSummary"] | null;
      /** Heat Treatment Lot */
      heat_treatment_lot: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      /** Lot */
      lot: string | null;
      /** Material Lot */
      material_lot: string | null;
      /** Notes */
      notes: string | null;
      revision: components["schemas"]["RevisionSummary"];
      /** Serial Number */
      serial_number: string | null;
      source: components["schemas"]["PartSource"];
      status: components["schemas"]["PartInstanceStatus"];
      /** Supplier Note */
      supplier_note: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /**
     * PartInstanceStatus
     * @enum {string}
     */
    PartInstanceStatus: "AVAILABLE" | "INSTALLED" | "REMOVED" | "SCRAPPED";
    /** PartInstanceSummary */
    PartInstanceSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      /** Serial Number */
      serial_number: string | null;
      source: components["schemas"]["PartSource"];
      status: components["schemas"]["PartInstanceStatus"];
    };
    /** PartInstanceUpdate */
    PartInstanceUpdate: {
      /** Heat Treatment Lot */
      heat_treatment_lot?: string | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      /** Lot */
      lot?: string | null;
      /** Material Lot */
      material_lot?: string | null;
      /** Notes */
      notes?: string | null;
      /** Serial Number */
      serial_number?: string | null;
      source?: components["schemas"]["PartSource"] | null;
      /** Supplier Note */
      supplier_note?: string | null;
    };
    /**
     * PartSource
     * @enum {string}
     */
    PartSource: "IN_HOUSE" | "PURCHASED" | "SALVAGED" | "OTHER";
    /** ProductCreate */
    ProductCreate: {
      /** Description */
      description?: string | null;
      /** Identifier */
      identifier: string;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      /** @default CONCEPT */
      lifecycle_state?: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
    };
    /** ProductModelCreate */
    ProductModelCreate: {
      /** Caliber Id */
      caliber_id?: string | null;
      /** Description */
      description?: string | null;
      /** Identifier */
      identifier: string;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      /** @default CONCEPT */
      lifecycle_state?: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Root Component Id */
      root_component_id?: string | null;
    };
    /** ProductModelRead */
    ProductModelRead: {
      caliber: components["schemas"]["CaliberSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      product: components["schemas"]["ProductSummary"];
      root_component: components["schemas"]["ComponentSummary"] | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** ProductModelSummary */
    ProductModelSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
    };
    /** ProductModelUpdate */
    ProductModelUpdate: {
      /** Caliber Id */
      caliber_id?: string | null;
      /** Description */
      description?: string | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      lifecycle_state?: components["schemas"]["LifecycleState"] | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Root Component Id */
      root_component_id?: string | null;
    };
    /** ProductRead */
    ProductRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Models */
      models: components["schemas"]["ProductModelSummary"][];
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** ProductSummary */
    ProductSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Name */
      name: string;
    };
    /** ProductUpdate */
    ProductUpdate: {
      /** Description */
      description?: string | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      lifecycle_state?: components["schemas"]["LifecycleState"] | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** PrototypeConfiguration */
    PrototypeConfiguration: {
      /** Count */
      count: number;
      prototype: components["schemas"]["PrototypeSummary"];
      /** Rows */
      rows: components["schemas"]["ConfigurationRow"][];
    };
    /** PrototypeCreate */
    PrototypeCreate: {
      /** Caliber Id */
      caliber_id?: string | null;
      /**
       * Identifier
       * @description Explicit identifier such as N1-P003; generated when omitted.
       */
      identifier?: string | null;
      /**
       * Is Placeholder
       * @default false
       */
      is_placeholder?: boolean;
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /**
       * Product Code
       * @description Used to generate {CODE}-P{NNN}.
       */
      product_code?: string | null;
      /** Product Model Id */
      product_model_id?: string | null;
      /** Purpose */
      purpose?: string | null;
      /** Started On */
      started_on?: string | null;
      /** @default PLANNED */
      status?: components["schemas"]["PrototypeStatus"];
    };
    /** PrototypeRead */
    PrototypeRead: {
      /** Build Count */
      build_count: number;
      caliber: components["schemas"]["CaliberSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Installed Count */
      installed_count: number;
      /** Is Placeholder */
      is_placeholder: boolean;
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      product_model: components["schemas"]["ProductModelSummary"] | null;
      /** Purpose */
      purpose: string | null;
      /** Retired On */
      retired_on: string | null;
      /** Started On */
      started_on: string | null;
      status: components["schemas"]["PrototypeStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /**
     * PrototypeStatus
     * @enum {string}
     */
    PrototypeStatus: "PLANNED" | "BUILDING" | "ACTIVE" | "RETIRED";
    /** PrototypeSummary */
    PrototypeSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identifier */
      identifier: string;
      /** Is Placeholder */
      is_placeholder: boolean;
      /** Name */
      name: string;
      status: components["schemas"]["PrototypeStatus"];
    };
    /** PrototypeUpdate */
    PrototypeUpdate: {
      /** Caliber Id */
      caliber_id?: string | null;
      /** Is Placeholder */
      is_placeholder?: boolean | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Product Model Id */
      product_model_id?: string | null;
      /** Purpose */
      purpose?: string | null;
      /** Retired On */
      retired_on?: string | null;
      /** Started On */
      started_on?: string | null;
      status?: components["schemas"]["PrototypeStatus"] | null;
    };
    /** RecentRevision */
    RecentRevision: {
      /** Change Summary */
      change_summary: string | null;
      component: components["schemas"]["ComponentSummary"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Frozen At */
      frozen_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Frozen */
      is_frozen: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Revision Label */
      revision_label: string;
      /** Revision Number */
      revision_number: number;
    };
    /**
     * RevisionContent
     * @description Editable engineering content of a revision. Every field optional.
     */
    RevisionContent: {
      /** Description */
      description?: string | null;
      /** Dimensions */
      dimensions?: {
        [key: string]: unknown;
      } | null;
      /** Finish */
      finish?: string | null;
      /** Heat Treatment */
      heat_treatment?: string | null;
      /** Inspection Requirements */
      inspection_requirements?: string | null;
      /** Manufacturing Method */
      manufacturing_method?: string | null;
      /** Mass G */
      mass_g?: number | string | null;
      /** Material */
      material?: string | null;
      /** Notes */
      notes?: string | null;
      /** Supplier Note */
      supplier_note?: string | null;
      /** Tolerances */
      tolerances?: {
        [key: string]: unknown;
      } | null;
    };
    /** RevisionCreate */
    RevisionCreate: {
      /** Change Summary */
      change_summary: string;
      /** @description Overrides applied on top of the copied content. */
      content?: components["schemas"]["RevisionContent"] | null;
      /**
       * Copy Bom
       * @description Copy the source revision's BOM lines.
       * @default true
       */
      copy_bom?: boolean;
      /**
       * From Revision Id
       * @description Source revision to copy from. Defaults to the latest.
       */
      from_revision_id?: string | null;
    };
    /** RevisionRead */
    RevisionRead: {
      /** Allowed Transitions */
      allowed_transitions: components["schemas"]["LifecycleState"][];
      /** Change Summary */
      change_summary: string | null;
      component: components["schemas"]["ComponentSummary"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Description */
      description?: string | null;
      /** Dimensions */
      dimensions?: {
        [key: string]: unknown;
      } | null;
      /** Display Identifier */
      display_identifier: string;
      /** Finish */
      finish?: string | null;
      /** Frozen At */
      frozen_at: string | null;
      /** Heat Treatment */
      heat_treatment?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Inspection Requirements */
      inspection_requirements?: string | null;
      /** Is Frozen */
      is_frozen: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Manufacturing Method */
      manufacturing_method?: string | null;
      /** Mass G */
      mass_g?: string | null;
      /** Material */
      material?: string | null;
      /** Notes */
      notes?: string | null;
      /** Revision Label */
      revision_label: string;
      /** Revision Number */
      revision_number: number;
      /** Superseded By Id */
      superseded_by_id: string | null;
      /** Supplier Note */
      supplier_note?: string | null;
      /** Tolerances */
      tolerances?: {
        [key: string]: unknown;
      } | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Updated By */
      updated_by: string;
    };
    /** RevisionSummary */
    RevisionSummary: {
      /** Change Summary */
      change_summary: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Frozen At */
      frozen_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Frozen */
      is_frozen: boolean;
      lifecycle_state: components["schemas"]["LifecycleState"];
      /** Revision Label */
      revision_label: string;
      /** Revision Number */
      revision_number: number;
    };
    /** RevisionUpdate */
    RevisionUpdate: {
      /** Change Summary */
      change_summary?: string | null;
      /** Description */
      description?: string | null;
      /** Dimensions */
      dimensions?: {
        [key: string]: unknown;
      } | null;
      /** Finish */
      finish?: string | null;
      /** Heat Treatment */
      heat_treatment?: string | null;
      /** Inspection Requirements */
      inspection_requirements?: string | null;
      /** Manufacturing Method */
      manufacturing_method?: string | null;
      /** Mass G */
      mass_g?: number | string | null;
      /** Material */
      material?: string | null;
      /** Notes */
      notes?: string | null;
      /** Supplier Note */
      supplier_note?: string | null;
      /** Tolerances */
      tolerances?: {
        [key: string]: unknown;
      } | null;
    };
    /** SystemInfo */
    SystemInfo: {
      /** Actor Id */
      actor_id: string;
      /** Actor Name */
      actor_name: string;
      /** Api Prefix */
      api_prefix: string;
      /** App Name */
      app_name: string;
      /** Environment */
      environment: string;
      /** Storage Backend */
      storage_backend: string;
      /** Storage Root */
      storage_root: string;
      /** Version */
      version: string;
    };
    /** TransitionRequest */
    TransitionRequest: {
      target_state: components["schemas"]["LifecycleState"];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WhereUsedRow */
    WhereUsedRow: {
      line: components["schemas"]["BomLineRead"];
      parent_component: components["schemas"]["ComponentSummary"];
      parent_revision: components["schemas"]["RevisionSummary"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_bom_line_api_v1_bom_lines__line_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomLineRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_bom_line_api_v1_bom_lines__line_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_bom_line_api_v1_bom_lines__line_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BomLineUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomLineRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_build_api_v1_builds__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildRecordRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_build_api_v1_builds__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BuildRecordUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildRecordRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_calibers_api_v1_calibers_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_CaliberRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_caliber_api_v1_calibers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaliberCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaliberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_caliber_api_v1_calibers__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaliberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_caliber_api_v1_calibers__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaliberUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaliberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_caliber_bom_api_v1_calibers__ref__bom_get: {
    parameters: {
      query?: {
        mode?: "latest" | "released";
      };
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomTree"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_components_api_v1_components_get: {
    parameters: {
      query?: {
        /** @description Search identifier or name */
        q?: string | null;
        family?: components["schemas"]["ComponentFamily"] | null;
        kind?: components["schemas"]["ComponentKind"] | null;
        /** @description State of the latest revision */
        state?: components["schemas"]["LifecycleState"] | null;
        placeholder?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ComponentRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_component_api_v1_components_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComponentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComponentDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_component_api_v1_components__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComponentDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_component_api_v1_components__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComponentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComponentDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_component_bom_api_v1_components__ref__bom_get: {
    parameters: {
      query?: {
        mode?: "latest" | "released";
      };
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomTree"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  component_part_instances_api_v1_components__ref__part_instances_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartInstanceRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_revisions_api_v1_components__ref__revisions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_revision_api_v1_components__ref__revisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevisionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_revision_by_label_api_v1_components__ref__revisions__label__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
        label: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_where_used_api_v1_components__ref__where_used_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WhereUsedRow"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dashboard_summary_api_v1_dashboard_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DashboardSummary"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  list_models_api_v1_models_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductModelRead"][];
        };
      };
    };
  };
  get_model_api_v1_models__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductModelRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_model_api_v1_models__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductModelUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductModelRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_model_bom_api_v1_models__ref__bom_get: {
    parameters: {
      query?: {
        mode?: "latest" | "released";
      };
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomTree"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_part_instances_api_v1_part_instances_get: {
    parameters: {
      query?: {
        /** @description Search instance, serial, component */
        q?: string | null;
        status?: components["schemas"]["PartInstanceStatus"] | null;
        component_id?: string | null;
        prototype_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PartInstanceRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_part_instances_api_v1_part_instances_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PartInstanceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartInstanceRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_part_instance_api_v1_part_instances__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartInstanceRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_part_instance_api_v1_part_instances__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PartInstanceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartInstanceRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_products_api_v1_products_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ProductRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_api_v1_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_product_api_v1_products__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_product_api_v1_products__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_product_models_api_v1_products__ref__models_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductModelRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_model_api_v1_products__ref__models_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductModelCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductModelRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_prototypes_api_v1_prototypes_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["PrototypeStatus"] | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PrototypeRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_prototype_api_v1_prototypes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PrototypeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrototypeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_prototype_api_v1_prototypes__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrototypeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_prototype_api_v1_prototypes__ref__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PrototypeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrototypeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_builds_api_v1_prototypes__ref__builds_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildRecordRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_build_api_v1_prototypes__ref__builds_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BuildRecordCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildRecordRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_configuration_api_v1_prototypes__ref__configuration_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrototypeConfiguration"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_revision_api_v1_revisions__revision_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_revision_api_v1_revisions__revision_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevisionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_bom_tree_api_v1_revisions__revision_id__bom_get: {
    parameters: {
      query?: {
        mode?: "latest" | "released";
      };
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomTree"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_bom_line_api_v1_revisions__revision_id__bom_lines_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BomLineCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomLineRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_bom_flat_api_v1_revisions__revision_id__bom_flat_get: {
    parameters: {
      query?: {
        mode?: "latest" | "released";
      };
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BomFlat"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revision_prototypes_api_v1_revisions__revision_id__prototypes_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrototypeSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transition_revision_api_v1_revisions__revision_id__transition_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        revision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_info_api_v1_system_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfo"];
        };
      };
    };
  };
}
